#!/usr/bin/env bun
// Pre-build assets the compiled binary needs at runtime but bun --compile
// can't bundle on its own:
//
//  - Webapp client bundles. Bun.build cannot run inside /$bunfs/ (no real
//    directory listings), so server.ts can't bundle the client on demand.
//    Solution: bake the bundles in as strings via src/web/embedded-client.ts.
//
//  - Opentui's tree-sitter parser worker. The library loads it via a
//    runtime-variable `new Worker(path)` that bun's static analyser can't
//    trace, so neither the worker file nor its `web-tree-sitter` dep get
//    bundled. We pre-bundle it for the `bun` target into a self-contained
//    JS file and let the TUI shim embed that copy via `with { type: "file" }`
//    and point OTUI_TREE_SITTER_WORKER_PATH at it.
//
// Writes:
//  - dist/client/main.js
//  - dist/client/pierre-worker.js
//  - src/web/embedded-client.ts        (string-export module, overwriting
//    the committed stub; restored by scripts/build-binary.ts after compile)
//  - src/tui/parser-worker-bundle.js   (self-contained worker, overwriting
//    the committed stub; restored by scripts/build-binary.ts after compile)

import { mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const distDir = resolve(ROOT, "dist/client");
await mkdir(distDir, { recursive: true });

async function bundle(entry: string, outName: string): Promise<string> {
  const r = await Bun.build({
    entrypoints: [entry],
    target: "browser",
    minify: false,
    define: { "process.env.NODE_ENV": JSON.stringify("production") },
    sourcemap: "none",
    naming: { entry: "[name].js" },
  });
  if (!r.success) {
    console.error(`bundle failed for ${entry}:`, JSON.stringify(r.logs));
    process.exit(1);
  }
  const out = r.outputs.find((o) => o.kind === "entry-point");
  if (!out) {
    console.error(`no entry-point output for ${entry}`);
    process.exit(1);
  }
  const text = await out.text();
  await writeFile(resolve(distDir, outName), text);
  return text;
}

// Bundle each entry separately. A single Bun.build call for both entries
// produces a 0-byte worker on bun 1.3.13 (looks like the output handles
// share state). Resolving the worker via `import.meta.resolve` instead of
// going through src/web/client/pierre-worker.ts bypasses the tree-shaker —
// @pierre/diffs declares only one file as a side-effect in package.json, so
// the shim's bare `import "@pierre/diffs/worker/worker.js"` gets elided to
// nothing when bundled as an entrypoint.
const workerEntry = fileURLToPath(import.meta.resolve("@pierre/diffs/worker/worker.js"));
const clientJs = await bundle(resolve(ROOT, "src/web/client/main.tsx"), "main.js");
const workerJs = await bundle(workerEntry, "pierre-worker.js");

if (!clientJs || !workerJs) {
  console.error(`missing entry output (client=${clientJs.length} worker=${workerJs.length})`);
  process.exit(1);
}

const embedded = `// GENERATED by scripts/build-client.ts during binary build.
// Empty stubs are committed at src/web/embedded-client.ts — the binary build
// pipeline overwrites this file with the real bundle strings, runs
// bun --compile, then restores the stub. server.ts uses these constants as
// the fast-path inside the compiled binary; dev mode (empty strings) falls
// through to runtime Bun.build.
export const EMBEDDED_CLIENT_JS: string = ${JSON.stringify(clientJs)};
export const EMBEDDED_PIERRE_WORKER_JS: string = ${JSON.stringify(workerJs)};
`;
await writeFile(resolve(ROOT, "src/web/embedded-client.ts"), embedded);

// Copy opentui's parser.worker.js into the committed stub at
// src/tui/parser-worker-bundle.js. The TUI shim then references it via
// `new Worker(new URL("./parser-worker-bundle.js", import.meta.url))` so
// bun --compile recognises it as a worker entrypoint and bundles its
// transitive deps (web-tree-sitter + tree-sitter.wasm) into the binary.
// We do a raw copy (not Bun.build) because we want bun --compile to
// process it as a fresh worker entrypoint — pre-bundling would emit a
// separate tree-sitter.wasm sibling that we can't ship inside /$bunfs/
// at a predictable path.
//
// The worker ships at the package root but isn't listed in `exports`, so
// we hop via the package entry (resolved through `@opentui/core`).
const { readFile: readFile2 } = await import("node:fs/promises");
const otuiPkgEntry = fileURLToPath(import.meta.resolve("@opentui/core"));
const otuiWorkerEntry = resolve(dirname(otuiPkgEntry), "parser.worker.js");
const otuiWorkerOut = resolve(ROOT, "src/tui/parser-worker-bundle.js");
const otuiWorkerJs = await readFile2(otuiWorkerEntry, "utf8");
await writeFile(otuiWorkerOut, otuiWorkerJs);

console.log(
  `built client (${clientJs.length}b) + worker (${workerJs.length}b) + copied otui-worker (${otuiWorkerJs.length}b)`,
);
